name: Publish Package to Github Packages

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://npm.pkg.github.com'
          scope: '@theofficialurban'

      - name: Install PNPM
        run: npm i -g pnpm

      - name: Install Packages
        run: pnpm i
      
      - name: Run Svelte Check
        run: pnpm run check

      - name: Publish Package
        if: ${{ !env.ACT }}
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
